name: رفع الملفات تلقائيًا

on:
  push:
    branches: [main]  # ابدأ العملية عند التحديث على فرع main

# الصلاحيات المطلوبة لتحميل الأكشنات ورفع الملفات
permissions:
  actions: read
  contents: write

jobs:
  upload-job:
    name: رفع الملفات
    runs-on: ubuntu-latest  # استخدم أحدث إصدار من الرنر

    steps:
      # الخطوة 1: تحميل الكود من الريبو
      - name: تحميل الكود
        uses: actions/checkout@v4  # إصدار حديث ومستقر

      # الخطوة 2: إنشاء ملف تجريبي (اختياري)
      - name: إنشاء ملف تجريبي
        run: |
          echo "هذا ملف تجريبي" > test.txt
          echo "تاريخ الإنشاء: $(date)" >> test.txt

      # الخطوة 3: رفع الملف كـ Artifact
      - name: رفع الملف
        uses: actions/upload-artifact@v4  # الإصدار v4 هنا
        with:
          name: ملفات-النتيجة
          path: |
            test.txt
            *.log  # يمكنك تغيير المسارات حسب احتياجك
          retention-days: 3  # احتفظ بالملفات لمدة 3 أيام

      # (اختياري) إرسال إشعار بالنجاح
      - name: إشعار بالتليجرام
        if: success()  # يعمل فقط إذا نجحت كل الخطوات السابقة
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "✅ تم رفع الملفات بنجاح!"
